# Date: 2024-1-21
# Author: Generated by GoCodeo.


import unittest 

from models.rectangle import Rectangle 

class TestRectangle(unittest.TestCase):

	    def test_create_rectangle(self):
	        rec_1 = Rectangle(4, 5)
	        self.assertEqual(rec_1.width, 4)
	        self.assertEqual(rec_1.height, 5)
	        self.assertEqual(rec_1.x, 0)
	        self.assertEqual(rec_1.y, 0)
	        self.assertIsNone(rec_1.id) 


